// <auto-generated />
using System;
using AspNetServer.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AspNetServer.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230812192119_Fix_FoodClassMigration")]
    partial class Fix_FoodClassMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.10");

            modelBuilder.Entity("AspNetServer.Data.Classes.CatheterClass", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Time")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Catheters");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Time = new DateTime(2023, 8, 12, 22, 21, 19, 714, DateTimeKind.Local).AddTicks(5344)
                        },
                        new
                        {
                            Id = 2,
                            Time = new DateTime(2023, 8, 11, 22, 21, 19, 714, DateTimeKind.Local).AddTicks(5350)
                        },
                        new
                        {
                            Id = 3,
                            Time = new DateTime(2023, 8, 10, 22, 21, 19, 714, DateTimeKind.Local).AddTicks(5355)
                        },
                        new
                        {
                            Id = 4,
                            Time = new DateTime(2023, 8, 9, 22, 21, 19, 714, DateTimeKind.Local).AddTicks(5359)
                        },
                        new
                        {
                            Id = 5,
                            Time = new DateTime(2023, 8, 8, 22, 21, 19, 714, DateTimeKind.Local).AddTicks(5364)
                        },
                        new
                        {
                            Id = 6,
                            Time = new DateTime(2023, 8, 7, 22, 21, 19, 714, DateTimeKind.Local).AddTicks(5369)
                        });
                });

            modelBuilder.Entity("AspNetServer.Data.Classes.FoodClass", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("BreadUnits")
                        .HasColumnType("REAL");

                    b.Property<double>("Dose")
                        .HasColumnType("REAL");

                    b.Property<string>("FoodName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("InsulinPinned")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("Time")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Food");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BreadUnits = 3.0,
                            Dose = 1.3,
                            FoodName = "bread, coffee",
                            InsulinPinned = 3.9000000000000004,
                            Time = new DateTime(2023, 8, 12, 22, 21, 19, 714, DateTimeKind.Local).AddTicks(5341)
                        },
                        new
                        {
                            Id = 2,
                            BreadUnits = 4.0,
                            Dose = 1.3,
                            FoodName = "bread, coffee",
                            InsulinPinned = 5.2000000000000002,
                            Time = new DateTime(2023, 8, 11, 22, 21, 19, 714, DateTimeKind.Local).AddTicks(5348)
                        },
                        new
                        {
                            Id = 3,
                            BreadUnits = 5.0,
                            Dose = 1.3,
                            FoodName = "bread, coffee",
                            InsulinPinned = 6.5,
                            Time = new DateTime(2023, 8, 10, 22, 21, 19, 714, DateTimeKind.Local).AddTicks(5353)
                        },
                        new
                        {
                            Id = 4,
                            BreadUnits = 6.0,
                            Dose = 1.3,
                            FoodName = "bread, coffee",
                            InsulinPinned = 7.8000000000000007,
                            Time = new DateTime(2023, 8, 9, 22, 21, 19, 714, DateTimeKind.Local).AddTicks(5358)
                        },
                        new
                        {
                            Id = 5,
                            BreadUnits = 7.0,
                            Dose = 1.3,
                            FoodName = "bread, coffee",
                            InsulinPinned = 9.0999999999999996,
                            Time = new DateTime(2023, 8, 8, 22, 21, 19, 714, DateTimeKind.Local).AddTicks(5362)
                        },
                        new
                        {
                            Id = 6,
                            BreadUnits = 8.0,
                            Dose = 1.3,
                            FoodName = "bread, coffee",
                            InsulinPinned = 10.4,
                            Time = new DateTime(2023, 8, 7, 22, 21, 19, 714, DateTimeKind.Local).AddTicks(5367)
                        });
                });

            modelBuilder.Entity("AspNetServer.Data.Classes.InsulinClass", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Time")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Insulin");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Time = new DateTime(2023, 8, 12, 22, 21, 19, 714, DateTimeKind.Local).AddTicks(5343)
                        },
                        new
                        {
                            Id = 2,
                            Time = new DateTime(2023, 8, 11, 22, 21, 19, 714, DateTimeKind.Local).AddTicks(5349)
                        },
                        new
                        {
                            Id = 3,
                            Time = new DateTime(2023, 8, 10, 22, 21, 19, 714, DateTimeKind.Local).AddTicks(5354)
                        },
                        new
                        {
                            Id = 4,
                            Time = new DateTime(2023, 8, 9, 22, 21, 19, 714, DateTimeKind.Local).AddTicks(5358)
                        },
                        new
                        {
                            Id = 5,
                            Time = new DateTime(2023, 8, 8, 22, 21, 19, 714, DateTimeKind.Local).AddTicks(5363)
                        },
                        new
                        {
                            Id = 6,
                            Time = new DateTime(2023, 8, 7, 22, 21, 19, 714, DateTimeKind.Local).AddTicks(5368)
                        });
                });

            modelBuilder.Entity("AspNetServer.Data.Classes.SugarClass", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("InsulinIncreased")
                        .HasColumnType("REAL");

                    b.Property<double>("Sugar")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("Time")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Sugars");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            InsulinIncreased = 0.0,
                            Sugar = 5.0999999999999996,
                            Time = new DateTime(2023, 8, 12, 22, 21, 19, 714, DateTimeKind.Local).AddTicks(5336)
                        },
                        new
                        {
                            Id = 2,
                            InsulinIncreased = 0.0,
                            Sugar = 5.2000000000000002,
                            Time = new DateTime(2023, 8, 11, 22, 21, 19, 714, DateTimeKind.Local).AddTicks(5347)
                        },
                        new
                        {
                            Id = 3,
                            InsulinIncreased = 0.0,
                            Sugar = 5.2999999999999998,
                            Time = new DateTime(2023, 8, 10, 22, 21, 19, 714, DateTimeKind.Local).AddTicks(5352)
                        },
                        new
                        {
                            Id = 4,
                            InsulinIncreased = 0.0,
                            Sugar = 5.4000000000000004,
                            Time = new DateTime(2023, 8, 9, 22, 21, 19, 714, DateTimeKind.Local).AddTicks(5357)
                        },
                        new
                        {
                            Id = 5,
                            InsulinIncreased = 0.0,
                            Sugar = 5.5,
                            Time = new DateTime(2023, 8, 8, 22, 21, 19, 714, DateTimeKind.Local).AddTicks(5362)
                        },
                        new
                        {
                            Id = 6,
                            InsulinIncreased = 0.0,
                            Sugar = 5.5999999999999996,
                            Time = new DateTime(2023, 8, 7, 22, 21, 19, 714, DateTimeKind.Local).AddTicks(5366)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
