// <auto-generated />
using System;
using AspNetServer.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AspNetServer.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230812191742_Add_Food_Insulin_Catheter_ClassesMigration")]
    partial class Add_Food_Insulin_Catheter_ClassesMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.10");

            modelBuilder.Entity("AspNetServer.Data.Classes.CatheterClass", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Time")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Catheters");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Time = new DateTime(2023, 8, 12, 22, 17, 42, 613, DateTimeKind.Local).AddTicks(1606)
                        },
                        new
                        {
                            Id = 2,
                            Time = new DateTime(2023, 8, 11, 22, 17, 42, 613, DateTimeKind.Local).AddTicks(1612)
                        },
                        new
                        {
                            Id = 3,
                            Time = new DateTime(2023, 8, 10, 22, 17, 42, 613, DateTimeKind.Local).AddTicks(1618)
                        },
                        new
                        {
                            Id = 4,
                            Time = new DateTime(2023, 8, 9, 22, 17, 42, 613, DateTimeKind.Local).AddTicks(1623)
                        },
                        new
                        {
                            Id = 5,
                            Time = new DateTime(2023, 8, 8, 22, 17, 42, 613, DateTimeKind.Local).AddTicks(1629)
                        },
                        new
                        {
                            Id = 6,
                            Time = new DateTime(2023, 8, 7, 22, 17, 42, 613, DateTimeKind.Local).AddTicks(1634)
                        });
                });

            modelBuilder.Entity("AspNetServer.Data.Classes.FoodClass", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("BreadUnits")
                        .HasColumnType("REAL");

                    b.Property<double>("Dose")
                        .HasColumnType("REAL");

                    b.Property<string>("FoodName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("InsulinPinned")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("Time")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Food");
                });

            modelBuilder.Entity("AspNetServer.Data.Classes.InsulinClass", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Time")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Insulin");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Time = new DateTime(2023, 8, 12, 22, 17, 42, 613, DateTimeKind.Local).AddTicks(1604)
                        },
                        new
                        {
                            Id = 2,
                            Time = new DateTime(2023, 8, 11, 22, 17, 42, 613, DateTimeKind.Local).AddTicks(1611)
                        },
                        new
                        {
                            Id = 3,
                            Time = new DateTime(2023, 8, 10, 22, 17, 42, 613, DateTimeKind.Local).AddTicks(1617)
                        },
                        new
                        {
                            Id = 4,
                            Time = new DateTime(2023, 8, 9, 22, 17, 42, 613, DateTimeKind.Local).AddTicks(1623)
                        },
                        new
                        {
                            Id = 5,
                            Time = new DateTime(2023, 8, 8, 22, 17, 42, 613, DateTimeKind.Local).AddTicks(1628)
                        },
                        new
                        {
                            Id = 6,
                            Time = new DateTime(2023, 8, 7, 22, 17, 42, 613, DateTimeKind.Local).AddTicks(1633)
                        });
                });

            modelBuilder.Entity("AspNetServer.Data.Classes.SugarClass", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("InsulinIncreased")
                        .HasColumnType("REAL");

                    b.Property<double>("Sugar")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("Time")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Sugars");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            InsulinIncreased = 0.0,
                            Sugar = 5.0999999999999996,
                            Time = new DateTime(2023, 8, 12, 22, 17, 42, 613, DateTimeKind.Local).AddTicks(1594)
                        },
                        new
                        {
                            Id = 2,
                            InsulinIncreased = 0.0,
                            Sugar = 5.2000000000000002,
                            Time = new DateTime(2023, 8, 11, 22, 17, 42, 613, DateTimeKind.Local).AddTicks(1609)
                        },
                        new
                        {
                            Id = 3,
                            InsulinIncreased = 0.0,
                            Sugar = 5.2999999999999998,
                            Time = new DateTime(2023, 8, 10, 22, 17, 42, 613, DateTimeKind.Local).AddTicks(1615)
                        },
                        new
                        {
                            Id = 4,
                            InsulinIncreased = 0.0,
                            Sugar = 5.4000000000000004,
                            Time = new DateTime(2023, 8, 9, 22, 17, 42, 613, DateTimeKind.Local).AddTicks(1620)
                        },
                        new
                        {
                            Id = 5,
                            InsulinIncreased = 0.0,
                            Sugar = 5.5,
                            Time = new DateTime(2023, 8, 8, 22, 17, 42, 613, DateTimeKind.Local).AddTicks(1626)
                        },
                        new
                        {
                            Id = 6,
                            InsulinIncreased = 0.0,
                            Sugar = 5.5999999999999996,
                            Time = new DateTime(2023, 8, 7, 22, 17, 42, 613, DateTimeKind.Local).AddTicks(1631)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
