// <auto-generated />
using AspNetServer.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AspNetServer.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230822115355_Add_Doses_Migration")]
    partial class Add_Doses_Migration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.10");

            modelBuilder.Entity("AspNetServer.Data.Classes.CatheterClass", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Time")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Catheters");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Time = "17:00"
                        },
                        new
                        {
                            Id = 2,
                            Time = "17:01"
                        },
                        new
                        {
                            Id = 3,
                            Time = "17:02"
                        },
                        new
                        {
                            Id = 4,
                            Time = "17:03"
                        },
                        new
                        {
                            Id = 5,
                            Time = "17:04"
                        },
                        new
                        {
                            Id = 6,
                            Time = "17:05"
                        });
                });

            modelBuilder.Entity("AspNetServer.Data.Classes.DosesClass", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Dose")
                        .HasColumnType("REAL");

                    b.Property<string>("EndTime")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StartTime")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Doses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Dose = 1.1000000000000001,
                            EndTime = "05:29",
                            StartTime = "00:00"
                        },
                        new
                        {
                            Id = 2,
                            Dose = 1.6000000000000001,
                            EndTime = "06:59",
                            StartTime = "05:30"
                        },
                        new
                        {
                            Id = 3,
                            Dose = 1.7,
                            EndTime = "11:29",
                            StartTime = "07:00"
                        },
                        new
                        {
                            Id = 4,
                            Dose = 1.3,
                            EndTime = "21:59",
                            StartTime = "11:30"
                        },
                        new
                        {
                            Id = 5,
                            Dose = 1.3999999999999999,
                            EndTime = "23:59",
                            StartTime = "22:00"
                        });
                });

            modelBuilder.Entity("AspNetServer.Data.Classes.FoodClass", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("BreadUnits")
                        .HasColumnType("REAL");

                    b.Property<double>("Dose")
                        .HasColumnType("REAL");

                    b.Property<string>("FoodName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("InsulinPinned")
                        .HasColumnType("REAL");

                    b.Property<string>("Time")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Food");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BreadUnits = 3.0,
                            Dose = 1.3,
                            FoodName = "bread, coffee",
                            InsulinPinned = 3.9000000000000004,
                            Time = "17:00"
                        },
                        new
                        {
                            Id = 2,
                            BreadUnits = 4.0,
                            Dose = 1.3,
                            FoodName = "bread, coffee",
                            InsulinPinned = 5.2000000000000002,
                            Time = "17:01"
                        },
                        new
                        {
                            Id = 3,
                            BreadUnits = 5.0,
                            Dose = 1.3,
                            FoodName = "bread, coffee",
                            InsulinPinned = 6.5,
                            Time = "17:02"
                        },
                        new
                        {
                            Id = 4,
                            BreadUnits = 6.0,
                            Dose = 1.3,
                            FoodName = "bread, coffee",
                            InsulinPinned = 7.8000000000000007,
                            Time = "17:03"
                        },
                        new
                        {
                            Id = 5,
                            BreadUnits = 7.0,
                            Dose = 1.3,
                            FoodName = "bread, coffee",
                            InsulinPinned = 9.0999999999999996,
                            Time = "17:04"
                        },
                        new
                        {
                            Id = 6,
                            BreadUnits = 8.0,
                            Dose = 1.3,
                            FoodName = "bread, coffee",
                            InsulinPinned = 10.4,
                            Time = "17:05"
                        });
                });

            modelBuilder.Entity("AspNetServer.Data.Classes.InsulinClass", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Time")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Insulin");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Time = "17:00"
                        },
                        new
                        {
                            Id = 2,
                            Time = "17:01"
                        },
                        new
                        {
                            Id = 3,
                            Time = "17:02"
                        },
                        new
                        {
                            Id = 4,
                            Time = "17:03"
                        },
                        new
                        {
                            Id = 5,
                            Time = "17:04"
                        },
                        new
                        {
                            Id = 6,
                            Time = "17:05"
                        });
                });

            modelBuilder.Entity("AspNetServer.Data.Classes.SugarClass", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("InsulinIncreased")
                        .HasColumnType("REAL");

                    b.Property<double>("Sugar")
                        .HasColumnType("REAL");

                    b.Property<string>("Time")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Sugars");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            InsulinIncreased = 0.0,
                            Sugar = 5.0999999999999996,
                            Time = "17:00"
                        },
                        new
                        {
                            Id = 2,
                            InsulinIncreased = 0.0,
                            Sugar = 5.2000000000000002,
                            Time = "17:01"
                        },
                        new
                        {
                            Id = 3,
                            InsulinIncreased = 0.0,
                            Sugar = 5.2999999999999998,
                            Time = "17:02"
                        },
                        new
                        {
                            Id = 4,
                            InsulinIncreased = 0.0,
                            Sugar = 5.4000000000000004,
                            Time = "17:03"
                        },
                        new
                        {
                            Id = 5,
                            InsulinIncreased = 0.0,
                            Sugar = 5.5,
                            Time = "17:04"
                        },
                        new
                        {
                            Id = 6,
                            InsulinIncreased = 0.0,
                            Sugar = 5.5999999999999996,
                            Time = "17:05"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
